In [16]:
import pandas as pd
xls = pd.ExcelFile('../data/excel/supermarket.xlsx')
# pd.ExcelFile('../data/excel/supermarket.xlsx').sheet_names
# data = pd.read_excel('../data/excel/supermarket.xlsx',
#  sheet_name=['invoice'])
# pd.read_excel(xls, sheet_name='invoice')
dfs = pd.read_excel(xls, sheet_name=['invoice', 'order_leads', 'sales_sql'])

In [18]:
type(dfs)
dfs.keys()

dict_keys(['invoice', 'order_leads', 'sales_sql'])

In [8]:
for df in data.values():
    display(pd.DataFrame(df))

,Order Id,Date,Meal Id,Company Id,Date of Meal,Participants,Meal Price,Type of Meal
0,839FKFW2LLX4LMBB,27-05-2016,INBUX904GIHI8YBD,LJKS5NK6788CYMUU,2016-05-31 07:00:00+02:00,['David Bishop'],469,Breakfast
1,97OX39BGVMHODLJM,27-09-2018,J0MMOOPP709DIDIE,LJKS5NK6788CYMUU,2018-10-01 20:00:00+02:00,['David Bishop'],22,Dinner
2,041ORQM5OIHTIU6L,24-08-2014,E4UJLQNCI16UX5CS,LJKS5NK6788CYMUU,2014-08-23 14:00:00+02:00,['Karen Stansell'],314,Lunch
3,YT796QI18WNGZ7ZJ,12-04-2014,C9SDFHF7553BE247,LJKS5NK6788CYMUU,2014-04-07 21:00:00+02:00,['Addie Patino'],438,Dinner
4,6YLROQT27B6HRF4E,28-07-2015,48EQXS6IHYNZDDZ5,LJKS5NK6788CYMUU,2015-07-27 14:00:00+02:00,['Addie Patino' 'Susan Guerrero'],690,Lunch
...,...,...,...,...,...,...,...,...
50012,4OMS8ZSA0UX8LHWI,20-09-2017,1TD5MROATV1NHZ4Y,E4K99D4JR9E40VE1,2017-09-21 08:00:00+02:00,['Regina Shirley'],9,Breakfast
50013,RR0VKJN8V0KHNKGG,19-03-2018,22EX9VZSJKHP4AIP,E4K99D4JR9E40VE1,2018-03-18 09:00:00+01:00,['Robin Ramos' 'Chester Mortimer'],25,Breakfast
50014,STJ6QJC30WPRM93H,21-09-2017,LMX18PNGWCIMG1QW,E4K99D4JR9E40VE1,2017-09-22 21:00:00+02:00,['Robin Ramos'],160,Dinner
50015,QHEUIYNC0XQX7GDR,28-01-2018,4U0VH2TGQL30X23X,E4K99D4JR9E40VE1,2018-02-01 21:00:00+01:00,['Chester Mortimer' 'Robin Ramos'],497,Dinner
50016,NKHFWT5I2J9LPAPG,06-09-2017,ORWFRT5TUSYGNYG7,E4K99D4JR9E40VE1,2017-09-09 14:00:00+02:00,['Chester Mortimer' 'Robin Ramos'],365,Lunch

In [17]:
# for df,sheet in data.items():
#     pd.DataFrame(sheet)
data = pd.ExcelFile('../data/excel/supermarket.xlsx')
data.sheet_names

['invoice', 'order_leads', 'sales_sql']